title: Samiullah's Portfolio
show_downloads: "true"
description: I'm an AI Developer with expertise in machine learning and back-end development, focused on creating scalable, AI-driven solutions. I specialize in NLP, neural networks, and fine-tuning models, with experience deploying advanced systems using GPT models and vector databases. My passion lies in integrating cutting-edge AI with robust back-end systems to solve complex problems and drive innovation.
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-assets
resume_link: "/assets/resume/Samiullah_Resume.pdf"


