title: Samiullah's Portfolio
show_downloads: "true" 
description: I'm an AI Developer with a passion for machine learning, back-end development, and building AI-driven solutions. 
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
